### ISSUE TITLE
Method 'GetServiceProviderHashCode' does not have an implementation

### ISSUE THREAD

**Issue by albertbaldi** [spasarto/EntityFrameworkCore.Ase#4]
System.TypeLoadException: Method 'GetServiceProviderHashCode' in type 'ExtensionInfo' from assembly 'EntityFrameworkCore.Ase, Version=3.1.2.1, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at EntityFrameworkCore.Ase.Internal.AseOptionsExtension.get_Info()
   at Microsoft.EntityFrameworkCore.DbContextOptions.GetHashCode()
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument)
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.GetOrAdd(IDbContextOptions options, Boolean providerRequired)
   at Microsoft.EntityFrameworkCore.DbContext..ctor(DbContextOptions options)
   at BMG.CR.ParametroServico.API.Data.SybaseContextDb..ctor(DbContextOptions`1 options)

**Comment by lord-andrius** [comment]
A current workaround is to use EntityFrameworkCore on version 3.1.21
